### ISSUE TITLE
Adding a room

### ISSUE THREAD

**Issue by jbone** [grupoarc/grouphug#10]
Adding a page should work, effectively, the same way as Moin and wikis in general:  going to a "well-formed" /page/... URI should create the page and open the editor if the page does not exist.  In conjunction, we should remove the add page form presently on the page list.

**Comment by jbone** [comment]
Ah, one amendment:  "if logged in"

**Comment by pjz** [comment]
Closed by https://github.com/grupoarc/grouphug/commit/46ecf2d3ca3acb88618a5bd69ddf26ee975a01ed
