### ISSUE TITLE
Editing a room

### ISSUE THREAD

**Issue by jbone** [grupoarc/grouphug#11]
Mechanism to put page in edit mode should be on page, not on page list.  Should only be available / visible if logged in.

**Comment by pjz** [comment]
What's the URL to edit a page?  `/page/mypage` shows the page... maybe `/edit/mypage` ?

**Comment by jbone** [comment]
Nonono --- don't embed verbs in the urls.

/page/<foo>?view=editor

**Comment by pjz** [comment]
Done in https://github.com/grupoarc/grouphug/commit/46ecf2d3ca3acb88618a5bd69ddf26ee975a01ed
