### ISSUE TITLE
Add chat

### ISSUE THREAD

**Issue by jbone** [grupoarc/grouphug#12]
Each page has an associated chat room.  This chat room is persistent.  It is only available to logged-in users, and --- eventually --- users that have access to that page, once we add access controls.  (We may want some users to have separate access to page and to chat room, for that matter.)

The chat room lives in the right hand panel.  This should be a style-able, distinct object.  I prefer "floating panels" to simple vertical column divisions, e.g., a small gutter around them, floating atop a background image.  (Separate issue re all that fukanka.)

**Comment by pjz** [comment]
Working but ugly as of https://github.com/grupoarc/grouphug/commit/05357cbf12714c2fe80b399936e8d8aa0ea497cc .
