### ISSUE TITLE
RecentChanges

### ISSUE THREAD

**Issue by jbone** [grupoarc/grouphug#16]
The "PagesList" needs to become "RecentChanges."

The "RecentChanges" list will have additional functionality eventually, and will be implemented in terms of embedded MarkdownDirectives (e.g. macros.)  For now, just the list is fine.

**Comment by pjz** [comment]
Ah, it can easily become RecentChanges if we just sort by last-modified time.

**Comment by pjz** [comment]
Currently we have `/room/roomname?view=history` ; I'm thinking that if `/room` (aka `/rooms`) is the Table of Contents, then something like `/room?view=history` could be 'Recent Changes'.  or should it be like `/room/roomname/history` and `/room/roomname/history/<YYYYMMDDHHMMSS>` ? ... that would make `/room/history` collide with a room named `history` which would be... bad.  Or should we keep it as `/room/roomname?view=history&t=YYYYMMDDHHMMSS` ?

**Comment by jbone** [comment]
Should be a parameter.  Use asof=<yymmdd.hhmmss>

**Comment by pjz** [comment]
`?view=history` and `?asof=YYYYMMDDHHMMSS` ?

**Comment by jbone** [comment]
Yup.  I'm thinking of "asof" as a kind of reduce operation that yields the 1 document representing the current version as of the indicated time.

**Comment by pjz** [comment]
Working impl in 117c1744a63ff68d4923c4ec7c940a29cd5d7456 , using unix timestamps (1s resolution) throughout.  If the URLs need to be more hackable we can later change to ISO8601 or something like YYMMDD.hhmmss or something, but that should be a different ticket.

**Comment by pjz** [comment]
Whoops! that fixed page history not 'Recent Changes'.   Related but not the same.

**Comment by pjz** [comment]
Implemented in 62cfd21fc38d6f0fef0f642b8beeab94b5103baf via `/rooms?view=history`
