### ISSUE TITLE
Uncreated rooms

### ISSUE THREAD

**Issue by pjz** [grupoarc/grouphug#18]
We need a template for an uncreated room - what someone sees the first time they visit a room URL that has not previously been visited.  I propose we create a special room named `__empty_room__` whose contents are shown in the above circumstances.

**Comment by pjz** [comment]
...and who can edit `__empty_room__` ?  How about anyone whose username is stored on the `__admins__` page?

**Comment by jbone** [comment]
I agree with both proposals.

**Comment by pjz** [comment]
also, the `__admins__` page can be edited by either anyone whose username is in the `__admins__` page, unless that page is empty, in which case by anyone.

**Comment by jbone** [comment]
That works for me

**Comment by pjz** [comment]
Done in https://github.com/grupoarc/grouphug/commit/46ecf2d3ca3acb88618a5bd69ddf26ee975a01ed
