### ISSUE TITLE
Support a WYSIWYG editor

### ISSUE THREAD

**Issue by pjz** [grupoarc/grouphug#20]
Start with http://ckeditor.com/ , I think?

**Comment by jbone** [comment]
Yup.  Inline, I think.

**Comment by pjz** [comment]
Another possibility: http://mindmup.github.io/bootstrap-wysiwyg/

**Comment by jbone** [comment]
Also this, which is actually native markdown:  http://hallojs.org

**Comment by jbone** [comment]
Also http://imperavi.com/redactor/

**Comment by pjz** [comment]
But we really like https://github.com/sofish/pen

**Comment by pjz** [comment]
Save HTML or Markdown ?

**Comment by jbone** [comment]
Markdown still, I think.

**Comment by pjz** [comment]
Back to http://ckeditor.com/ ; Currently saving HTML, can switch later if we need it.
