### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by jbone** [grupoarc/grouphug#23]
Placeholder:  need to be able to upload / attach arbitrary attachments.

**Comment by pjz** [comment]
What's the URL space for attachments look like?  Using something like `/room/pagename/attachments` means effectively disallowing slashes in room names.

**Comment by jbone** [comment]
I think we need either (a) a general collection e.g. /items or /objects, and or (b) a file / attachment specific collection, e.g. /files.

We should be doing name mapping, generally, rather than forcing the "contains" hierarchy into the URL-space.  (It seems unmeteor-like and as you note impairs subpages / places constraints on other forms of naming...)

**Comment by pjz** [comment]
Should they be versioned themselves, or part of a room that's versioned?  Would there be a reason for, for example, a room to point to multiple versions of an attachment? or is the single latest version all that's needed?

**Comment by jbone** [comment]
I think they should be stored by hash and linked by hash, with the name maintained as metadata.  Then versioning the page is sufficient;  if a new attachment is added, a new version of the page is created with a list of the current attachment hashes?

**Comment by pjz** [comment]
so they're stored (unversioned) as `/data/<hash>`, with links to them in pages ?   How does access control to them work? Maybe they go under `/data/<pagename>/<hash>` and inherit `<pagename>`'s access controls? behind the scenes we can de-dup.

**Comment by jbone** [comment]
Yeah, that works

**Comment by pjz** [comment]
Note that RESTful stuff was punted in favor of just using [CollectionFS](https://github.com/CollectionFS/Meteor-CollectionFS).  Implemented in https://github.com/grupoarc/grouphug/commit/0eb84a2e8ace3c1f309b07d77b9dbd6c1e1e3f2c.
