### ISSUE TITLE
Feature: database (room + users + chat) dump and restore

### ISSUE THREAD

**Issue by pjz** [grupoarc/grouphug#25]
Dump to json or something. Mongo may do some or all of this?

**Comment by pjz** [comment]
Should we dump chat too?

**Comment by jbone** [comment]
Json, rooms + chat, yes.

jb

**Comment by pjz** [comment]
What do the URIs for this look like? `/backup.gz` and `/restore` ? or `/admin/` with links to those?

**Comment by jbone** [comment]
I think /admin/backups w ?action=dump and action=restore, w the latter supporting asof=zzzz

**Comment by pjz** [comment]
So, like [app-dump](https://github.com/hitchcott/app-dump) ?

**Comment by jbone** [comment]
Hmm, 'k?

**Comment by pjz** [comment]
Done in https://github.com/grupoarc/grouphug/commit/150b29107c61910c17974ae3e962eb1ca102f2ec
