### ISSUE TITLE
Modernize helper declarations

### ISSUE THREAD

**Issue by pjz** [grupoarc/grouphug#27]
According to the denizens of #meteor

``` javascript

// Deprecated way to attach template helpers (dont use)
Template.templateName.helpers.someHelper = function(){
  // Do something
}
Template.templateName.helpers.anotherHelper = function(){
  // Do something
}

// Attaching helpers to templates - is scoped to template
Template.templateName.helpers({
  someHelper: function(){
    // Do something
  },
  anotherHelper: function(){
    // Do something else
  }
});


// ES2015 
Template.templateName.helpers({
  someHelper(){
    // Do something
  },
  anotherHelper(){
    // Do something
  }
});
```

...so we should switch to one of the latter two usages.

**Comment by jbone** [comment]
I think the middle option is probably best.  Syntax is valid <ES6 as well, not that that's really important, but it's also more economical than the older version.

**Comment by pjz** [comment]
Sure, but why not just go full ES6? It's all happily polyfilled and will be old hat soon.  Honestly I don't really care, just curious as to why not.

**Comment by jbone** [comment]
I find this particular syntax, in the context of dictionaries, unappetizing?  ;-)

**Comment by jbone** [comment]
There's a certain isomorphism w/ the earlier syntax:  names are names and functions are values and the binding between them is explicit.  Given the Javascript object model in general, and prototype-based systems in particular, I find it a better option.  Plus, until everyone converts to ES6, using the new-new could result in mixed style in an app?  I dunno.  Just a quirk, I suppose.

**Comment by pjz** [comment]
'k.  Looks like it's done already.
