### ISSUE TITLE
Add test infrastructure

### ISSUE THREAD

**Issue by pjz** [grupoarc/grouphug#4]
Let's use tox, I've heard good things about it.  If not, we can fall back to py.test.  Or maybe they're orthogonal.  I'll investigate.

**Comment by pjz** [comment]
tox is automation of stuff that I've already automated in the Makefile.  Orthogonal to py.test. What we've got works for now. We'll use tox if our env gets more complicated.

**Comment by jbone** [comment]
Does I need to need to pulled etc or did you already do whatever's necessary?
